# Generated by Django 3.2.3 on 2024-04-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='elder',
            field=models.BooleanField(default=False, verbose_name='Староста'),
        ),
    ]
