# Generated by Django 5.0.4 on 2024-04-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_group_teachers_alter_teacher_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='in_college',
            field=models.BooleanField(default=False, verbose_name='В колледже'),
        ),
    ]
